services:
  frontend:
    build:
      context: ./pdf-translator
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./translated:/app/translated
      - ./shared:/app/shared:ro  # Mount shared modules
      - ./backend:/app/backend:ro  # Mount backend code for development
    environment:
      - UPLOAD_FOLDER=/app/uploads
      - TRANSLATED_FOLDER=/app/translated
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app:/app/shared
      - DEBUG=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads
      - ./translated:/app/translated
      - ./shared:/app/shared:ro  # Mount shared modules
      - ./worker:/app/worker:ro  # Mount worker code for development
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - TRANSLATED_FOLDER=/app/translated
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONPATH=/app:/app/shared
      - DEBUG=true
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
